export const VOICE_MAX_RECORDING_MS = 90 * 1000;
export const VOICE_MAX_UPLOAD_BYTES = 10 * 1024 * 1024;
export const VOICE_MIME_CANDIDATES = ['audio/mp4', 'audio/webm;codecs=opus', 'audio/webm'];
export const VOICE_DIALOG_SILENCE_MS = 900;
export const VOICE_DIALOG_MIN_RECORDING_MS = 600;
export const VOICE_DIALOG_LEVEL_THRESHOLD = 0.018;
export const VOICE_DIALOG_SILENCE_AUDIO =
  'data:audio/wav;base64,UklGRiYAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQIAAAAAAA==';
export const REALTIME_VOICE_SAMPLE_RATE = 24000;
export const REALTIME_VOICE_BUFFER_SIZE = 2048;
export const REALTIME_VOICE_MIN_TURN_MS = 500;
export const REALTIME_VOICE_BARGE_IN_LEVEL_THRESHOLD = 0.026;
export const REALTIME_VOICE_BARGE_IN_SUSTAIN_MS = 180;
